services:
  mysql:
    container_name: mysql_container
    image: mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: '!@Skdud340'
      MYSQL_DATABASE: trello

  redis:
    container_name: redis_container
    image: redis
    ports:
      - 6379:6379


  backend:
    container_name: trello_container
    image: nayoun340/trello
    expose:
      - 8080
    ports:
      - 8080:8080
    depends_on:
      - mysql
      - redis