spring:
  profiles:
    active: dev

cloud:
  aws:
    s3:
      bucket: ${BUCKET}
    stack.auto: false
    region.static: ${REGION_STATIC}
    credentials:
      accessKey: ${ACCESS_KEY}
      secretKey: ${SECRET_KEY}