name: 'CI'

on:
  pull_request:
    branches: [ dev ]

jobs:
  ci:
    runs-on: [ ubuntu-latest ]
    steps:
      - name: 나의 깃헙 코드를 깃헙 액션의 VM에 옮기는 작업 중 ...
        uses: actions/checkout@v4

      - name: 깃헙 액션의 VM에 자바 설치중 ...
        uses: actions/setup-java@v4
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: dev yml 파일 생성
        run: |
          echo "${{ secrets.APPLICATION_DEV_YML }}" > ./application-dev.yml
        shell: bash

      - name: yml 파일 생성
        run: |
          echo "${{ secrets.APPLICATION_YML_LOCAL }}" > ./application.yml
        shell: bash

      - name: VM내의 (도커 컨테이너를 활용하여) MySQL 구동 시키기
        uses: mirromutth/mysql-action@v1.1
        with:
          mysql database: trello
          mysql root password: ${{secrets.MYSQL_PASSWORD}}

      - name: 빌드 및 테스트 코드 돌리는중 ... (Only Test)
        run: |
          chmod +x ./gradlew
          ./gradlew test

      - name: 오류명 상세히 알려줌
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: build/test-results/test